version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
